name: Proxy Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build and start server
      run: |
        nohup npm start &
        sleep 5s  # Подождем, чтобы сервер успел стартовать

    - name: Publish to GitHub Pages
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git branch -D gh-pages || true
        git checkout -B gh-pages
        cp -r ./* .
        git add .
        git commit -m "Publish to GitHub Pages"
        git push -u origin gh-pages
